# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutonomousSport' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AutonomousSport
  pod 'OpenTok', '2.15.0'


  target 'AutonomousSportTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AutonomousSport-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AutonomousSport-tvOS

  target 'AutonomousSport-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
